// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CancelScan():Promise<void>;

export function DeleteFiles(arg1:Array<string>):Promise<models.DeleteOperation>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetDuplicateGroups():Promise<Array<models.DuplicateGroup>>;

export function GetOperationHistory():Promise<Array<models.DeleteOperation>>;

export function GetSettings():Promise<models.ScanSettings>;

export function GetVersion():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.ScanSettings):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartScan(arg1:models.ScanSettings):Promise<void>;
