// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelScan():Promise<void>;

export function DeleteFiles(arg1:Array<string>):Promise<models.DeleteOperation>;

export function GetDuplicateGroups():Promise<Array<models.DuplicateGroup>>;

export function GetOperationHistory():Promise<Array<models.DeleteOperation>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartScan(arg1:Array<string>,arg2:number):Promise<void>;
